export const articles = [
  {
    id: "1",
    author: "Rian Saputra",
    thumbnail: "https://placehold.co/600x400",
    alt: "Gambar ilustrasi AI",
    publishAt: "2024-07-10T08:30:00.000Z",
    title: "Mengenal AI: Masa Depan Teknologi Dunia",
    slug: "mengenal-ai-masa-depan-teknologi",
    description:
      "Artificial Intelligence menjadi teknologi yang banyak digunakan dalam berbagai bidang mulai dari industri, kesehatan, hingga pendidikan. Artikel ini membahas potensi dan tantangan yang menyertainya secara mendalam.",
    stats: { valueIncrease: 12.0, valueDecrease: 2.0 },
  },
  {
    id: "2",
    author: "Aulia Rahman",
    thumbnail: "https://placehold.co/600x400",
    alt: "Ilustrasi startup",
    publishAt: "2024-06-15T10:00:00.000Z",
    title: "Perkembangan Startup di Indonesia",
    slug: "perkembangan-startup-indonesia",
    description:
      "Startup Indonesia berkembang pesat dalam 5 tahun terakhir. Banyak anak muda yang terjun ke dunia bisnis digital dengan inovasi yang menjanjikan dan berdampak besar bagi perekonomian nasional.",
    stats: { valueIncrease: 20.0, valueDecrease: 1.0 },
  },
  {
    id: "3",
    author: "Dewi Kartika",
    thumbnail: "https://placehold.co/600x400",
    alt: "Gambar coding",
    publishAt: "2024-05-21T14:45:00.000Z",
    title: "Tips Belajar Coding untuk Pemula",
    slug: "tips-belajar-coding-pemula",
    description:
      "Belajar coding tidaklah sesulit yang dibayangkan. Dengan pendekatan yang tepat dan konsistensi, siapa pun bisa menguasai bahasa pemrograman dan membuat aplikasi mereka sendiri.",
    stats: { valueIncrease: 15.0, valueDecrease: 3.0 },
  },
  {
    id: "4",
    author: "Galih Prasetyo",
    thumbnail: "https://placehold.co/600x400",
    alt: "Smart city Indonesia",
    publishAt: "2024-06-01T09:15:00.000Z",
    title: "Konsep Smart City di Era Digital",
    slug: "konsep-smart-city-digital",
    description:
      "Smart City adalah konsep pengelolaan kota dengan teknologi digital untuk meningkatkan kualitas hidup masyarakat. Artikel ini membahas penerapan konsep tersebut di berbagai kota di Indonesia.",
    stats: { valueIncrease: 18.0, valueDecrease: 0.0 },
  },
  {
    id: "5",
    author: "Intan Lestari",
    thumbnail: "https://placehold.co/600x400",
    alt: "Desain UI/UX",
    publishAt: "2024-05-10T13:30:00.000Z",
    title: "Pentingnya UI/UX dalam Pengembangan Aplikasi",
    slug: "pentingnya-uiux-dalam-aplikasi",
    description:
      "Desain UI/UX berperan penting dalam keberhasilan sebuah aplikasi. User interface yang intuitif dan user experience yang memuaskan akan membuat pengguna betah dan loyal.",
    stats: { valueIncrease: 22.0, valueDecrease: 1.0 },
  },
  {
    id: "6",
    author: "Nanda Fadhilah",
    thumbnail: "https://placehold.co/600x400",
    alt: "Logo startup",
    publishAt: "2024-04-18T11:20:00.000Z",
    title: "5 Startup Lokal yang Go Internasional",
    slug: "startup-lokal-go-internasional",
    description:
      "Beberapa startup asal Indonesia berhasil menembus pasar global. Kisah mereka memberikan inspirasi dan semangat bagi pelaku usaha baru untuk terus berinovasi dan berkembang.",
    stats: { valueIncrease: 25.0, valueDecrease: 2.0 },
  },
  {
    id: "7",
    author: "Fajar Nugroho",
    thumbnail: "https://placehold.co/600x400",
    alt: "Sistem keamanan digital",
    publishAt: "2024-06-22T07:00:00.000Z",
    title: "Keamanan Siber di Tengah Dunia Digital",
    slug: "keamanan-siber-dunia-digital",
    description:
      "Di era digital, keamanan siber menjadi hal yang sangat krusial. Artikel ini membahas bagaimana menjaga data pribadi dan sistem dari serangan siber yang semakin kompleks.",
    stats: { valueIncrease: 14.0, valueDecrease: 4.0 },
  },
  {
    id: "8",
    author: "Putri Amelia",
    thumbnail: "https://placehold.co/600x400",
    alt: "Laptop dengan data statistik",
    publishAt: "2024-07-01T12:00:00.000Z",
    title: "Data Analytics untuk Bisnis Modern",
    slug: "data-analytics-bisnis-modern",
    description:
      "Data analytics membantu bisnis memahami konsumen dan meningkatkan efisiensi operasional. Temukan manfaat, tantangan, dan alat-alat populer dalam artikel ini.",
    stats: { valueIncrease: 16.0, valueDecrease: 1.0 },
  },
  {
    id: "9",
    author: "Bayu Mahendra",
    thumbnail: "https://placehold.co/600x400",
    alt: "Gadget terbaru 2024",
    publishAt: "2024-06-10T17:10:00.000Z",
    title: "Review Gadget Terbaru Tahun Ini",
    slug: "review-gadget-terbaru-2024",
    description:
      "Tahun 2024 menghadirkan banyak inovasi di dunia gadget. Mulai dari smartphone lipat hingga wearable canggih. Simak ulasan lengkapnya di sini.",
    stats: { valueIncrease: 10.0, valueDecrease: 0.0 },
  },
  {
    id: "10",
    author: "Siti Mulyani",
    thumbnail: "https://placehold.co/600x400",
    alt: "Tim kerja kolaboratif",
    publishAt: "2024-05-25T08:45:00.000Z",
    title: "Kolaborasi Tim di Era Remote Work",
    slug: "kolaborasi-tim-remote-work",
    description:
      "Bekerja dari jarak jauh menuntut kolaborasi yang efisien. Teknologi hadir untuk menjawab tantangan ini, namun peran komunikasi dan kepercayaan tetaplah kunci utama.",
    stats: { valueIncrease: 19.0, valueDecrease: 3.0 },
  },
  {
    id: "11",
    author: "Andi Nugraha",
    thumbnail: "https://placehold.co/600x400",
    alt: "Cloud computing illustration",
    publishAt: "2024-04-12T15:30:00.000Z",
    title: "Mengapa Cloud Computing Semakin Populer?",
    slug: "mengapa-cloud-computing-populer",
    description:
      "Cloud computing menawarkan fleksibilitas, efisiensi, dan skalabilitas bagi perusahaan. Artikel ini membahas alasan di balik meningkatnya adopsi cloud di berbagai industri.",
    stats: { valueIncrease: 21.0, valueDecrease: 2.0 },
  },
  {
    id: "12",
    author: "Laras Setiawan",
    thumbnail: "https://placehold.co/600x400",
    alt: "Ilustrasi blockchain",
    publishAt: "2024-05-01T10:10:00.000Z",
    title: "Blockchain Lebih dari Sekadar Kripto",
    slug: "blockchain-lebih-dari-kripto",
    description:
      "Teknologi blockchain tidak hanya terbatas pada cryptocurrency. Banyak sektor mulai memanfaatkannya untuk keamanan data, logistik, hingga layanan publik.",
    stats: { valueIncrease: 13.0, valueDecrease: 1.0 },
  },
];
